substitutions:
  hostname: 'dc-meter'
  devicename: HWC DC Meter
web_server:
  port: 80
esphome:
  name: $hostname
  platform: ESP32
  board: nodemcu-32s
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
logger:

uart:
  tx_pin: GPIO22
  rx_pin: GPIO23
  baud_rate: 9600
  stop_bits: 1

sensor:
  - platform: pzemdc
    current:
      name: "PZEM-003 Current"
    voltage:
      name: "PZEM-003 Voltage"
    power:
      name: "PZEM-003 Power"
    energy:
      name: "PZEM-003 Energy"
    update_interval: 30s